USE [GD2C2021]

DROP TABLE IF EXISTS LA_LOLA_ROTICERIA.MATERIAL
DROP TABLE IF EXISTS LA_LOLA_ROTICERIA.MATERIAL_X_TAREA
DROP TABLE IF EXISTS LA_LOLA_ROTICERIA.PAQUETE
DROP TABLE IF EXISTS LA_LOLA_ROTICERIA.TAREA_ASIGNADA
DROP TABLE IF EXISTS LA_LOLA_ROTICERIA.TAREA
DROP TABLE IF EXISTS LA_LOLA_ROTICERIA.TIPO_TAREA
DROP TABLE IF EXISTS LA_LOLA_ROTICERIA.ORDEN_TRABAJO
DROP TABLE IF EXISTS LA_LOLA_ROTICERIA.MECANICO
DROP TABLE IF EXISTS LA_LOLA_ROTICERIA.TALLER
DROP TABLE IF EXISTS LA_LOLA_ROTICERIA.ESTADO
DROP TABLE IF EXISTS LA_LOLA_ROTICERIA.VIAJE
DROP TABLE IF EXISTS LA_LOLA_ROTICERIA.RECORRIDO
DROP TABLE IF EXISTS LA_LOLA_ROTICERIA.CIUDAD
DROP TABLE IF EXISTS LA_LOLA_ROTICERIA.CHOFER
DROP TABLE IF EXISTS LA_LOLA_ROTICERIA.TIPO_PAQUETE
DROP TABLE IF EXISTS LA_LOLA_ROTICERIA.CAMION
DROP TABLE IF EXISTS LA_LOLA_ROTICERIA.MODELO_CAMION
DROP TABLE IF EXISTS LA_LOLA_ROTICERIA.MARCA

DROP SCHEMA IF EXISTS LA_LOLA_ROTICERIA