USE [GD2C2021]

DROP TABLE LA_LOLA_ROTICERIA.MATERIAL
DROP TABLE LA_LOLA_ROTICERIA.MATERIAL_X_TAREA
DROP TABLE LA_LOLA_ROTICERIA.PAQUETE
DROP TABLE LA_LOLA_ROTICERIA.TAREA_ASIGNADA
DROP TABLE LA_LOLA_ROTICERIA.TAREA
DROP TABLE LA_LOLA_ROTICERIA.TIPO_TAREA
DROP TABLE LA_LOLA_ROTICERIA.ORDEN_TRABAJO
DROP TABLE LA_LOLA_ROTICERIA.MECANICO
DROP TABLE LA_LOLA_ROTICERIA.TALLER
DROP TABLE LA_LOLA_ROTICERIA.ESTADO
DROP TABLE LA_LOLA_ROTICERIA.VIAJE
DROP TABLE LA_LOLA_ROTICERIA.RECORRIDO
DROP TABLE LA_LOLA_ROTICERIA.CIUDAD
DROP TABLE LA_LOLA_ROTICERIA.CHOFER
DROP TABLE LA_LOLA_ROTICERIA.TIPO_PAQUETE
DROP TABLE LA_LOLA_ROTICERIA.CAMION
DROP TABLE LA_LOLA_ROTICERIA.MODELO_CAMION
DROP TABLE LA_LOLA_ROTICERIA.MARCA

DROP SCHEMA LA_LOLA_ROTICERIA