USE [GD2C2021]

DROP TABLE ESQUEMA.MATERIAL
DROP TABLE ESQUEMA.MATERIAL_X_TAREA
DROP TABLE ESQUEMA.RECORRIDO
DROP TABLE ESQUEMA.PAQUETE
DROP TABLE ESQUEMA.TAREA_ASIGNADA
DROP TABLE ESQUEMA.TALLER
DROP TABLE ESQUEMA.CIUDAD
DROP TABLE ESQUEMA.TAREA
DROP TABLE ESQUEMA.TIPO_TAREA
DROP TABLE ESQUEMA.ORDEN_TRABAJO
DROP TABLE ESQUEMA.MECANICO
DROP TABLE ESQUEMA.ESTADO
DROP TABLE ESQUEMA.VIAJE
DROP TABLE ESQUEMA.CHOFER
DROP TABLE ESQUEMA.TIPO_PAQUETE
DROP TABLE ESQUEMA.CAMION
DROP TABLE ESQUEMA.MODELO_CAMION
DROP TABLE ESQUEMA.MARCA

DROP SCHEMA ESQUEMA