USE [GD2C2021]

-- CREACION DEL ESQUEMA
GO
CREATE SCHEMA LA_LOLA_ROTICERIA
GO

CREATE TABLE LA_LOLA_ROTICERIA.MARCA(
	MARCA_ID INT PRIMARY KEY IDENTITY(1,1),
	MARCA_NOMBRE NVARCHAR(255)
)

CREATE TABLE LA_LOLA_ROTICERIA.MATERIAL(
	MATERIAL_ID INT PRIMARY KEY IDENTITY(1,1),
	MATERIAL_NOMBRE NVARCHAR(255),
	MATERIAL_DESCRIPCION NVARCHAR(255)
)

CREATE TABLE LA_LOLA_ROTICERIA.TIPO_TAREA(
	TIPO_TAREA_ID INT PRIMARY KEY IDENTITY(1,1),
	TIPO_TAREA_TIPO NVARCHAR(255),
	TIPO_TAREA_DESCRIPCION NVARCHAR(255)
)

CREATE TABLE LA_LOLA_ROTICERIA.TAREA(
	TAREA_ID INT PRIMARY KEY IDENTITY(1,1),
	TAREA_NOMBRE NVARCHAR(255),
	TAREA_DESCRIPCION NVARCHAR(255),
	TAREA_TIPO_ID INT REFERENCES LA_LOLA_ROTICERIA.TIPO_TAREA(TIPO_TAREA_ID)
)

CREATE TABLE LA_LOLA_ROTICERIA.MATERIAL_X_TAREA(
	MATERIAL_X_TAREA_MATERIAL_ID INT,
	MATERIAL_X_TAREA_TAREA_ID INT,
	MATERIAL_X_TAREA_CANTIDAD INT
)

CREATE TABLE LA_LOLA_ROTICERIA.CIUDAD(
	CIUDAD_ID INT PRIMARY KEY IDENTITY(1,1),
	CIUDAD_NOMBRE NVARCHAR(255)
)

CREATE TABLE LA_LOLA_ROTICERIA.ESTADO(
	ESTADO_ID INT PRIMARY KEY IDENTITY(1,1),
	ESTADO_DESCRIPCION NVARCHAR(255)
)

CREATE TABLE LA_LOLA_ROTICERIA.RECORRIDO(
	RECORRIDO_ID INT PRIMARY KEY IDENTITY(1,1),
	RECORRIDO_CIUDAD_ORIGEN INT REFERENCES LA_LOLA_ROTICERIA.CIUDAD(CIUDAD_ID),
	RECORRIDO_CIUDAD_DESTINO INT REFERENCES LA_LOLA_ROTICERIA.CIUDAD(CIUDAD_ID),
	RECORRIDO_KM_RECORIDOS INT,
	RECORRIDO_PRECIO_RECORRIDO DECIMAL(18,2)
)

CREATE TABLE LA_LOLA_ROTICERIA.MODELO_CAMION(
	MODELO_CAMION_ID INT PRIMARY KEY IDENTITY(1,1),
	MODELO_CAMION_DESCRIPCION NVARCHAR(255),
	MODELO_CAMION_VELOCIDAD_MAXIMA INT,
	MODELO_CAMION_CAPACIDAD_TANQUE INT,
	MODELO_CAMION_CAPACIDAD_CARGA INT,
	MODELO_CAMION_MARCA_ID INT REFERENCES LA_LOLA_ROTICERIA.MARCA(MARCA_ID)
)

CREATE TABLE LA_LOLA_ROTICERIA.CAMION(
	CAMION_PATENTE NVARCHAR(255) PRIMARY KEY,
	CAMION_NRO_CHASIS NVARCHAR(255), 
	CAMION_NRO_MOTOR NVARCHAR(255),
	CAMION_FECHA_ALTA DATETIME2(3),
	CAMION_MODELO_ID INT REFERENCES LA_LOLA_ROTICERIA.MODELO_CAMION(MODELO_CAMION_ID)
)

CREATE TABLE LA_LOLA_ROTICERIA.CHOFER(
	CHOFER_NRO_LEGAJO INT PRIMARY KEY,
	CHOFER_NOMBRE NVARCHAR(255),
	CHOFER_APELLIDO NVARCHAR(255),
	CHOFER_DNI DECIMAL(18,2), 
	CHOFER_DIRECCION NVARCHAR(255),
	CHOFER_TELEFONO INT,
	CHOFER_MAIL NVARCHAR(255),
	CHOFER_FECHA_NACIMIENTO DATETIME2(3),
	CHOFER_COSTO_HORA INT
)

CREATE TABLE LA_LOLA_ROTICERIA.VIAJE(
	VIAJE_NRO INT PRIMARY KEY IDENTITY(1,1),
	VIAJE_CAMION_ID NVARCHAR(255) REFERENCES LA_LOLA_ROTICERIA.CAMION(CAMION_PATENTE),
	VIAJE_CHOFER_ID INT REFERENCES LA_LOLA_ROTICERIA.CHOFER(CHOFER_NRO_LEGAJO), 
	VIAJE_FECHA_INICIO DATETIME2(7),
	VIAJE_FECHA_FIN DATETIME2(3),
	VIAJE_CONSUMO_COMBUSTIBLE DECIMAL(18,2),
	VIAJE_CANTIDAD_PAQUETES INT,
	VIAJE_RECORIDO_ID INT REFERENCES LA_LOLA_ROTICERIA.RECORRIDO(RECORRIDO_ID)
)

CREATE TABLE LA_LOLA_ROTICERIA.TIPO_PAQUETE(
	TIPO_PAQUETE_ID INT PRIMARY KEY IDENTITY(1,1),
	TIPO_PAQUETE_DESCRIPCION NVARCHAR(255),
	TIPO_PAQUETE_ANCHO_MAXIMO DECIMAL(18,2),
	TIPO_PAQUETE_ALTO_MAXIMO DECIMAL(18,2),
	TIPO_PAQUETE_LARGO_MAXIMO DECIMAL(18,2),
	TIPO_PAQUETE_PESO_MAXIMO DECIMAL(18,2),
	TIPO_PAQUETE_PRECIO DECIMAL(18,2)
)

CREATE TABLE LA_LOLA_ROTICERIA.PAQUETE(
	PAQUETE_ID INT PRIMARY KEY IDENTITY(1,1),
	PAQUETE_VIAJE_ID INT REFERENCES LA_LOLA_ROTICERIA.VIAJE(VIAJE_NRO),
	PAQUETE_PRECIO_FINAL DECIMAL(18,2),
	PAQUETE_TIPO_ID INT REFERENCES LA_LOLA_ROTICERIA.TIPO_PAQUETE(TIPO_PAQUETE_ID)
)

CREATE TABLE LA_LOLA_ROTICERIA.ORDEN_TRABAJO(
	ORDEN_TRABAJO_NRO INT PRIMARY KEY,
	ORDEN_TRABAJO_CAMION_ID NVARCHAR(255) REFERENCES LA_LOLA_ROTICERIA.CAMION(CAMION_PATENTE),
	ORDEN_TRABAJO_FECHA_GENERACION NVARCHAR(255),
	ORDEN_TRABAJO_ESTADO_ID INT REFERENCES LA_LOLA_ROTICERIA.ESTADO(ESTADO_ID)
)

CREATE TABLE LA_LOLA_ROTICERIA.TALLER(
	TALLER_ID INT PRIMARY KEY IDENTITY(1,1),
	TALLER_DIRECCION NVARCHAR(255),
	TALLER_TELEFONO DECIMAL(18,0),
	TALLER_MAIL NVARCHAR(255),
	TALLER_NOMBRE NVARCHAR(255),
	TALLER_CIUDAD_ID INT REFERENCES LA_LOLA_ROTICERIA.CIUDAD(CIUDAD_ID)
)

CREATE TABLE LA_LOLA_ROTICERIA.MECANICO(
	MECANICO_NRO_LEGAJO INT PRIMARY KEY,
	MECANICO_TALLER_ID INT REFERENCES LA_LOLA_ROTICERIA.TALLER(TALLER_ID),
	MECANICO_NOMBRE NVARCHAR(255),
	MECANICO_APELLIDO NVARCHAR(255),
	MECANICO_DNI DECIMAL(18,2),
	MECANICO_DIRECCION NVARCHAR(255),
	MECANICO_TELEFONO INT,
	MECANICO_MAIL NVARCHAR(255),
	MECANICO_FECHA_NACIMIENTO DATETIME2(3),
	MECANICO_COSTO_HORA INT
)

CREATE TABLE LA_LOLA_ROTICERIA.TAREA_ASIGNADA(
	TAREA_ASIGNADA_CODIGO INT PRIMARY KEY IDENTITY(1,1),
	TAREA_ASIGNADA_MECANICO_ID INT REFERENCES LA_LOLA_ROTICERIA.MECANICO(MECANICO_NRO_LEGAJO),
	TAREA_ASIGNADA_TAREA_ID INT REFERENCES LA_LOLA_ROTICERIA.TAREA(TAREA_ID),
	TAREA_ASIGNADA_TIEMPO_DE_EJECUCION_ESTIMADO INT,
	TAREA_ASIGNADA_TIEMPO_DE_EJECUCION_REAL INT,
	TAREA_ASIGNADA_FECHA_INICIO_ESTIMADA DATETIME2(3),
	TAREA_ASIGNADA_FECHA_INICIO_REAL DATETIME2(3),
	TAREA_ASIGNADA_FECHA_FIN DATETIME2(3),
	TAREA_ASIGNADA_ORDEN_TRABAJO_ID INT REFERENCES LA_LOLA_ROTICERIA.ORDEN_TRABAJO(ORDEN_TRABAJO_NRO)
)