USE [GD2C2021]

DROP TABLE IF EXISTS LA_LOLA_ROTICERIA.MATERIAL
DROP TABLE IF EXISTS LA_LOLA_ROTICERIA.MATERIAL_X_TAREA
DROP TABLE IF EXISTS LA_LOLA_ROTICERIA.PAQUETE
DROP TABLE IF EXISTS LA_LOLA_ROTICERIA.TAREA_ASIGNADA
DROP TABLE IF EXISTS LA_LOLA_ROTICERIA.TAREA
DROP TABLE IF EXISTS LA_LOLA_ROTICERIA.TIPO_TAREA
DROP TABLE IF EXISTS LA_LOLA_ROTICERIA.ORDEN_TRABAJO
DROP TABLE IF EXISTS LA_LOLA_ROTICERIA.MECANICO
DROP TABLE IF EXISTS LA_LOLA_ROTICERIA.TALLER
DROP TABLE IF EXISTS LA_LOLA_ROTICERIA.ESTADO
DROP TABLE IF EXISTS LA_LOLA_ROTICERIA.VIAJE
DROP TABLE IF EXISTS LA_LOLA_ROTICERIA.RECORRIDO
DROP TABLE IF EXISTS LA_LOLA_ROTICERIA.CIUDAD
DROP TABLE IF EXISTS LA_LOLA_ROTICERIA.CHOFER
DROP TABLE IF EXISTS LA_LOLA_ROTICERIA.TIPO_PAQUETE
DROP TABLE IF EXISTS LA_LOLA_ROTICERIA.CAMION
DROP TABLE IF EXISTS LA_LOLA_ROTICERIA.MODELO_CAMION
DROP TABLE IF EXISTS LA_LOLA_ROTICERIA.MARCA

DROP SCHEMA IF EXISTS LA_LOLA_ROTICERIA

-- CREACION DEL ESQUEMA
GO
CREATE SCHEMA LA_LOLA_ROTICERIA
GO

CREATE TABLE LA_LOLA_ROTICERIA.MARCA(
	ID INT PRIMARY KEY IDENTITY(1,1),
	NOMBRE NVARCHAR(255)
)

CREATE TABLE LA_LOLA_ROTICERIA.MATERIAL(
	ID INT PRIMARY KEY IDENTITY(1,1),
	NOMBRE NVARCHAR(255),
	DESCRIPCION NVARCHAR(255)
)

CREATE TABLE LA_LOLA_ROTICERIA.TIPO_TAREA(
	ID INT PRIMARY KEY IDENTITY(1,1),
	TIPO NVARCHAR(255),
	DESCRIPCION NVARCHAR(255)
)

CREATE TABLE LA_LOLA_ROTICERIA.TAREA(
	ID INT PRIMARY KEY IDENTITY(1,1),
	NOMBRE NVARCHAR(255),
	DESCRIPCION NVARCHAR(255),
	TIPO_ID INT REFERENCES LA_LOLA_ROTICERIA.TIPO_TAREA(ID)
)

CREATE TABLE LA_LOLA_ROTICERIA.MATERIAL_X_TAREA(
	MATERIAL_ID INT,
	TAREA_ID INT,
	CANTIDAD INT
)

CREATE TABLE LA_LOLA_ROTICERIA.CIUDAD(
	ID INT PRIMARY KEY IDENTITY(1,1),
	NOMBRE NVARCHAR(255)
)

CREATE TABLE LA_LOLA_ROTICERIA.ESTADO(
	ID INT PRIMARY KEY IDENTITY(1,1),
	DESCRIPCION NVARCHAR(255)
)

CREATE TABLE LA_LOLA_ROTICERIA.RECORRIDO(
	ID INT PRIMARY KEY IDENTITY(1,1),
	CIUDAD_ORIGEN INT REFERENCES LA_LOLA_ROTICERIA.CIUDAD(ID),
	CIUDAD_DESTINO INT REFERENCES LA_LOLA_ROTICERIA.CIUDAD(ID),
	KM_RECORIDOS INT,
	PRECIO_RECORRIDO DECIMAL(18,2)
)

CREATE TABLE LA_LOLA_ROTICERIA.MODELO_CAMION(
	ID INT PRIMARY KEY IDENTITY(1,1),
	DESCRIPCION NVARCHAR(255),
	VELOCIDAD_MAXIMA INT,
	CAPACIDAD_TANQUE INT,
	CAPACIDAD_CARGA INT,
	MARCA_ID INT REFERENCES LA_LOLA_ROTICERIA.MARCA(ID)
)

CREATE TABLE LA_LOLA_ROTICERIA.CAMION(
	PATENTE NVARCHAR(255) PRIMARY KEY,
	NRO_CHASIS NVARCHAR(255), 
	NRO_MOTOR NVARCHAR(255),
	FECHA_ALTA DATETIME2(3),
	MODELO_ID INT REFERENCES LA_LOLA_ROTICERIA.MODELO_CAMION(ID)
)

CREATE TABLE LA_LOLA_ROTICERIA.CHOFER(
	NRO_LEGAJO INT PRIMARY KEY,
	NOMBRE NVARCHAR(255),
	APELLIDO NVARCHAR(255),
	DNI DECIMAL(18,2), 
	DIRECCION NVARCHAR(255),
	TELEFONO INT,
	MAIL NVARCHAR(255),
	FECHA_NACIMIENTO DATETIME2(3),
	COSTO_HORA INT
)

CREATE TABLE LA_LOLA_ROTICERIA.VIAJE(
	VIAJE_NRO INT PRIMARY KEY IDENTITY(1,1),
	CAMION_ID NVARCHAR(255) REFERENCES LA_LOLA_ROTICERIA.CAMION(PATENTE),
	CHOFER_ID INT REFERENCES LA_LOLA_ROTICERIA.CHOFER(NRO_LEGAJO), 
	FECHA_INICIO DATETIME2(7),
	FECHA_FIN DATETIME2(3),
	CONSUMO_COMBUSTIBLE DECIMAL(18,2),
	CANTIDAD_PAQUETES INT,
	RECORIDO_ID INT REFERENCES LA_LOLA_ROTICERIA.RECORRIDO(ID)
)

CREATE TABLE LA_LOLA_ROTICERIA.TIPO_PAQUETE(
	ID INT PRIMARY KEY IDENTITY(1,1),
	DESCRIPCION NVARCHAR(255),
	ANCHO_MAXIMO DECIMAL(18,2),
	ALTO_MAXIMO DECIMAL(18,2),
	LARGO_MAXIMO DECIMAL(18,2),
	PESO_MAXIMO DECIMAL(18,2),
	PRECIO DECIMAL(18,2)
)

CREATE TABLE LA_LOLA_ROTICERIA.PAQUETE(
	ID INT PRIMARY KEY IDENTITY(1,1),
	VIAJE_ID INT REFERENCES LA_LOLA_ROTICERIA.VIAJE(VIAJE_NRO),
	PRECIO_FINAL DECIMAL(18,2),
	TIPO_ID INT REFERENCES LA_LOLA_ROTICERIA.TIPO_PAQUETE(ID)
)

CREATE TABLE LA_LOLA_ROTICERIA.ORDEN_TRABAJO(
	NRO INT PRIMARY KEY,
	CAMION_ID NVARCHAR(255) REFERENCES LA_LOLA_ROTICERIA.CAMION(PATENTE),
	FECHA_GENERACION NVARCHAR(255),
	ESTADO_ID INT REFERENCES LA_LOLA_ROTICERIA.ESTADO(ID)
)

CREATE TABLE LA_LOLA_ROTICERIA.TALLER(
	ID INT PRIMARY KEY IDENTITY(1,1),
	DIRECCION NVARCHAR(255),
	TELEFONO DECIMAL(18,0),
	MAIL NVARCHAR(255),
	NOMBRE NVARCHAR(255),
	CIUDAD_ID INT REFERENCES LA_LOLA_ROTICERIA.CIUDAD(ID)
)

CREATE TABLE LA_LOLA_ROTICERIA.MECANICO(
	NRO_LEGAJO INT PRIMARY KEY,
	TALLER_ID INT REFERENCES LA_LOLA_ROTICERIA.TALLER(ID),
	NOMBRE NVARCHAR(255),
	APELLIDO NVARCHAR(255),
	DNI DECIMAL(18,2),
	DIRECCION NVARCHAR(255),
	TELEFONO INT,
	MAIL NVARCHAR(255),
	FECHA_NACIMIENTO DATETIME2(3),
	COSTO_HORA INT
)

CREATE TABLE LA_LOLA_ROTICERIA.TAREA_ASIGNADA(
	CODIGO INT PRIMARY KEY IDENTITY(1,1),
	MECANICO_ID INT REFERENCES LA_LOLA_ROTICERIA.MECANICO(NRO_LEGAJO),
	TAREA_ID INT REFERENCES LA_LOLA_ROTICERIA.TAREA(ID),
	TIEMPO_DE_EJECUCION_ESTIMADO INT,
	TIEMPO_DE_EJECUCION_REAL INT,
	FECHA_INICIO_ESTIMADA DATETIME2(3),
	FECHA_INICIO_REAL DATETIME2(3),
	FECHA_FIN DATETIME2(3),
	ORDEN_TRABAJO_ID INT REFERENCES LA_LOLA_ROTICERIA.ORDEN_TRABAJO(NRO)
)



-------------- MIGRACION --
--CIUDAD
INSERT INTO LA_LOLA_ROTICERIA.CIUDAD (NOMBRE)
	SELECT distinct RECORRIDO_CIUDAD_DESTINO ciudad
	FROM gd_esquema.Maestra
	WHERE RECORRIDO_CIUDAD_DESTINO is not null
	UNION
	SELECT distinct RECORRIDO_CIUDAD_ORIGEN ciudad
	FROM gd_esquema.Maestra
	WHERE RECORRIDO_CIUDAD_ORIGEN is not null

--RECORRIDO
INSERT INTO LA_LOLA_ROTICERIA.RECORRIDO (CIUDAD_ORIGEN, CIUDAD_DESTINO, KM_RECORIDOS, PRECIO_RECORRIDO)
	SELECT distinct (SELECT c.ID FROM LA_LOLA_ROTICERIA.CIUDAD c WHERE c.NOMBRE = RECORRIDO_CIUDAD_ORIGEN), 
	       (SELECT c.ID FROM LA_LOLA_ROTICERIA.CIUDAD c WHERE c.NOMBRE = RECORRIDO_CIUDAD_DESTINO), 		   
		   RECORRIDO_KM, 
		   RECORRIDO_PRECIO
	FROM gd_esquema.Maestra
	WHERE RECORRIDO_CIUDAD_DESTINO is not null
	or RECORRIDO_CIUDAD_ORIGEN is not null
	or RECORRIDO_PRECIO is not null

--MARCA
INSERT INTO LA_LOLA_ROTICERIA.MARCA (NOMBRE)
	SELECT distinct MARCA_CAMION_MARCA
	FROM gd_esquema.Maestra
	WHERE MARCA_CAMION_MARCA is not null

--MODELO CAMION
INSERT INTO LA_LOLA_ROTICERIA.MODELO_CAMION (DESCRIPCION, CAPACIDAD_CARGA, CAPACIDAD_TANQUE, VELOCIDAD_MAXIMA, MARCA_ID)	
	SELECT MODELO_CAMION, MODELO_CAPACIDAD_CARGA, MODELO_CAPACIDAD_TANQUE, MODELO_VELOCIDAD_MAX, (select ID from LA_LOLA_ROTICERIA.MARCA m where m.NOMBRE =  MARCA_CAMION_MARCA)
	FROM gd_esquema.Maestra
	WHERE MODELO_CAMION is not null
	GROUP BY MODELO_CAMION, MODELO_CAPACIDAD_CARGA, MODELO_CAPACIDAD_TANQUE, MODELO_VELOCIDAD_MAX, MARCA_CAMION_MARCA

--CAMION
INSERT INTO LA_LOLA_ROTICERIA.CAMION (PATENTE, NRO_CHASIS, NRO_MOTOR, FECHA_ALTA, MODELO_ID)	
	SELECT distinct CAMION_PATENTE, CAMION_NRO_CHASIS, CAMION_NRO_MOTOR, CAMION_FECHA_ALTA, (select m.ID from LA_LOLA_ROTICERIA.MODELO_CAMION m where m.DESCRIPCION = MODELO_CAMION and m.CAPACIDAD_CARGA = MODELO_CAPACIDAD_CARGA)
	FROM gd_esquema.Maestra
	WHERE CAMION_NRO_CHASIS is not null

--CHOFER
INSERT INTO LA_LOLA_ROTICERIA.CHOFER (NRO_LEGAJO, NOMBRE, APELLIDO, DNI, DIRECCION, TELEFONO, MAIL, FECHA_NACIMIENTO, COSTO_HORA)
	SELECT distinct CHOFER_NRO_LEGAJO, CHOFER_NOMBRE, CHOFER_APELLIDO, CHOFER_DNI, CHOFER_DIRECCION, CHOFER_TELEFONO, CHOFER_MAIL, CHOFER_FECHA_NAC, CHOFER_COSTO_HORA
	FROM gd_esquema.Maestra
	WHERE CHOFER_NRO_LEGAJO is not null

--VIAJE
INSERT INTO LA_LOLA_ROTICERIA.VIAJE (RECORIDO_ID, CAMION_ID, CHOFER_ID, FECHA_INICIO, FECHA_FIN, CONSUMO_COMBUSTIBLE, CANTIDAD_PAQUETES)
	SELECT distinct (select r.ID 
					from LA_LOLA_ROTICERIA.RECORRIDO r 
					where r.CIUDAD_DESTINO = (select c.ID from LA_LOLA_ROTICERIA.CIUDAD c where c.NOMBRE = RECORRIDO_CIUDAD_DESTINO)
					and r.CIUDAD_ORIGEN = (select c.ID from LA_LOLA_ROTICERIA.CIUDAD c where c.NOMBRE = RECORRIDO_CIUDAD_ORIGEN) 
					and r.PRECIO_RECORRIDO = RECORRIDO_PRECIO 
					and r.PRECIO_RECORRIDO = RECORRIDO_PRECIO), 
					CAMION_PATENTE, CHOFER_NRO_LEGAJO, VIAJE_FECHA_INICIO, VIAJE_FECHA_FIN, VIAJE_CONSUMO_COMBUSTIBLE, PAQUETE_CANTIDAD
	FROM gd_esquema.Maestra
	WHERE VIAJE_FECHA_FIN is not null

--TIPO_PAQUETE
INSERT INTO LA_LOLA_ROTICERIA.TIPO_PAQUETE (DESCRIPCION, ANCHO_MAXIMO, ALTO_MAXIMO, LARGO_MAXIMO, PESO_MAXIMO, PRECIO)
	SELECT distinct PAQUETE_DESCRIPCION, PAQUETE_ANCHO_MAX, PAQUETE_ALTO_MAX, PAQUETE_LARGO_MAX, PAQUETE_PESO_MAX, PAQUETE_PRECIO
	FROM gd_esquema.Maestra
	WHERE PAQUETE_DESCRIPCION IS NOT NULL

--PAQUETE
INSERT INTO LA_LOLA_ROTICERIA.PAQUETE ( VIAJE_ID, TIPO_ID, PRECIO_FINAL)
	SELECT (select v.VIAJE_NRO
			from LA_LOLA_ROTICERIA.VIAJE v
			inner join LA_LOLA_ROTICERIA.RECORRIDO r on v.RECORIDO_ID = r.ID
			inner join LA_LOLA_ROTICERIA.CHOFER chof on v.CHOFER_ID = chof.NRO_LEGAJO
			inner join LA_LOLA_ROTICERIA.CAMION cam on v.CAMION_ID = cam.PATENTE
			where v.CANTIDAD_PAQUETES = m.PAQUETE_CANTIDAD
			and v.CONSUMO_COMBUSTIBLE = m.VIAJE_CONSUMO_COMBUSTIBLE
			and v.FECHA_INICIO = m.VIAJE_FECHA_INICIO
			and v.FECHA_FIN = m.VIAJE_FECHA_FIN
			and r.KM_RECORIDOS = m.RECORRIDO_KM
			and r.PRECIO_RECORRIDO = m.RECORRIDO_PRECIO
			and chof.NRO_LEGAJO = m.CHOFER_NRO_LEGAJO
			and cam.PATENTE = m.CAMION_PATENTE),
		  (select t_p.ID
		   from LA_LOLA_ROTICERIA.TIPO_PAQUETE t_p
		   where t_p.DESCRIPCION = m.PAQUETE_DESCRIPCION),
		   m.PAQUETE_PRECIO + m.RECORRIDO_PRECIO
	FROM gd_esquema.Maestra m
	WHERE PAQUETE_DESCRIPCION IS NOT NULL
